/* =====================================================
   PROMPTFORGE AI v4
   GENERATOR.JS
===================================================== */

function generateProfessionalPrompt(){

    const template=
PromptTemplates[data.detect.industry]||
PromptTemplates.General;

        return;

    }

    const detect=smartDetect(idea);

    updateDetectResult(detect);

    const category=
    document.getElementById("category").value==="Auto Detect"
    ?detect.category
    :document.getElementById("category").value;

    const style=
    document.getElementById("style").value==="Auto Detect"
    ?detect.style
    :document.getElementById("style").value;

    const ai=
    document.getElementById("ai").value;

    const size=
    document.getElementById("size").value;

    const prompt=buildProfessionalPrompt({

        idea,

        detect,

        category,

        style,

        ai,

        size

    });

    document.getElementById("output").value=prompt;

    updateQuality(prompt);

    if(typeof saveHistory==="function"){

        saveHistory(prompt);

    }

}

function buildProfessionalPrompt(data){

const negative=promptDB.negativePrompt.join(", ");

const camera=promptDB.camera.join(", ");

const print=promptDB.printing.join(", ");

const aiOpt=promptDB.aiOptimization.join(", ");

return `

# PROFESSIONAL AI DESIGN PROMPT

==================================================

PROJECT

${data.idea}

==================================================

CATEGORY

${data.category}

STYLE

${data.style}

TARGET AI

${data.ai}

CANVAS

${data.size}

==================================================

OBJECTIVE

Create a premium quality ${data.category} that immediately attracts attention.

The final result must look professional,
commercial,
modern,
and visually outstanding.

==================================================

VISUAL DIRECTION

• Strong visual hierarchy

• Premium composition

• Large main object

• Eye-catching focal point

• Professional typography

• Modern spacing

• Clean alignment

• Balanced layout

• Rich visual storytelling

==================================================

COLOR STRATEGY

Primary Color

${data.detect.color}

Use professional color grading.

High contrast.

Premium saturation.

Rich shadows.

==================================================

TARGET AUDIENCE

${data.detect.audience}

==================================================

LIGHTING & CAMERA

${camera}

==================================================

PRINT SPECIFICATION

${print}

==================================================

AI OPTIMIZATION

${aiOpt}

==================================================

NEGATIVE PROMPT

${negative}

==================================================

FINAL QUALITY

Ultra HD

8K

HDR

Professional

Commercial Grade

Award Winning

Best Quality

Masterpiece

==================================================

Generated by PromptForge AI v4

`;

}

function updateDetectResult(result){

document.getElementById("detectCategory").textContent=result.category;

document.getElementById("detectStyle").textContent=result.style;

document.getElementById("detectColor").textContent=result.color;

document.getElementById("detectAudience").textContent=result.audience;

}
