/* =====================================================
   PROMPTFORGE AI v3.5
   GENERATOR.JS
===================================================== */

function generateProfessionalPrompt() {

    const idea = document.getElementById("idea").value.trim();

    if (!idea) {

        alert("Silakan masukkan ide desain terlebih dahulu.");

        return;

    }

    const detect = smartDetect(idea);

    const category =
        document.getElementById("category").value === "Auto Detect"
        ? detect.category
        : document.getElementById("category").value;

    const style =
        document.getElementById("style").value === "Auto Detect"
        ? detect.style
        : document.getElementById("style").value;

    const size =
        document.getElementById("size").value;

    const ai =
        document.getElementById("ai").value;

    updateDetectResult(detect);

    const prompt = buildPrompt({

        idea,

        category,

        style,

        size,

        ai,

        detect

    });

    document.getElementById("output").value = prompt;

    updateQuality(prompt);

    if (typeof saveHistory === "function") {

        saveHistory(prompt);

    }

}

function buildPrompt(data) {

    const camera =
        promptDB.camera.join(", ");

    const negative =
        promptDB.negativePrompt.join(", ");

    const aiOpt =
        promptDB.aiOptimization.join(", ");

    const print =
        promptDB.printing.join(", ");

    return `# PROFESSIONAL AI DESIGN PROMPT

==================================================

PROJECT

${data.idea}

==================================================

CATEGORY

${data.category}

STYLE

${data.style}

TARGET AI

${data.ai}

CANVAS SIZE

${data.size}

==================================================

OBJECTIVE

Create a premium quality ${data.category} with a highly professional appearance suitable for commercial use.

==================================================

VISUAL DIRECTION

• Strong visual hierarchy

• Premium composition

• Eye-catching focal point

• Balanced spacing

• Modern layout

• Professional typography

• Clean alignment

• Rich visual storytelling

==================================================

COLOR DIRECTION

Primary Color :
${data.detect.color}

Use harmonious color grading.

High contrast.

Premium color balance.

==================================================

TARGET AUDIENCE

${data.detect.audience}

==================================================

LIGHTING

${camera}

==================================================

PRINT SPECIFICATION

${print}

==================================================

AI OPTIMIZATION

${aiOpt}

==================================================

NEGATIVE PROMPT

${negative}

==================================================

OUTPUT REQUIREMENTS

Ultra HD

8K

HDR

Professional Quality

Commercial Design

Print Ready

==================================================

Generated by PromptForge AI v3.5`;

}

function updateDetectResult(result) {

    document.getElementById("detectCategory").textContent = result.category;

    document.getElementById("detectStyle").textContent = result.style;

    document.getElementById("detectColor").textContent = result.color;

    document.getElementById("detectAudience").textContent = result.audience;

}
