/* =====================================================
   PROMPTFORGE AI v4
   GENERATOR.JS
===================================================== */

function generateProfessionalPrompt() {

    const idea = document.getElementById("idea").value.trim();

    if (idea === "") {
        alert("Silakan masukkan ide desain terlebih dahulu.");
        return;
    }

    const detect = smartDetect(idea);

    updateDetectResult(detect);

    const category =
        document.getElementById("category").value === "Auto Detect"
            ? detect.category
            : document.getElementById("category").value;

    const style =
        document.getElementById("style").value === "Auto Detect"
            ? detect.style
            : document.getElementById("style").value;

    const size = document.getElementById("size").value;

    const ai = document.getElementById("ai").value;

    const prompt = buildProfessionalPrompt({

        idea,
        detect,
        category,
        style,
        size,
        ai

    });

    document.getElementById("output").value = prompt;

    updateQuality(prompt);

    if (typeof saveHistory === "function") {
        saveHistory(prompt);
    }

}


/* =====================================================
   BUILD PROMPT
===================================================== */

function buildProfessionalPrompt(data) {

    const template =
        PromptTemplates[data.detect.industry] ||
        PromptTemplates.General;

    const negative =
        promptDB.negativePrompt.join(", ");

    const camera =
        promptDB.camera.join(", ");

    const printing =
        promptDB.printing.join(", ");

    const aiOptimization =
        promptDB.aiOptimization.join(", ");

    return `# PROFESSIONAL AI DESIGN PROMPT

==================================================

PROJECT

${data.idea}

==================================================

CATEGORY

${data.category}

STYLE

${data.style}

TARGET AI

${data.ai}

CANVAS SIZE

${data.size}

==================================================

OBJECTIVE

${template.objective}

==================================================

COMPOSITION

${template.composition}

==================================================

TYPOGRAPHY

${template.typography}

==================================================

LIGHTING

${template.lighting}

==================================================

CAMERA

${template.camera}

==================================================

VISUAL DIRECTION

• Strong visual hierarchy

• Premium composition

• Eye-catching focal point

• Modern layout

• Professional typography

• Balanced spacing

• Rich visual storytelling

• Commercial quality

==================================================

COLOR STRATEGY

Primary Color

${data.detect.color}

Use premium color grading.

High contrast.

Balanced saturation.

Professional harmony.

==================================================

TARGET AUDIENCE

${data.detect.audience}

==================================================

INDUSTRY

${data.detect.industry}

==================================================

PLATFORM

${data.detect.platform}

==================================================

MOOD

${data.detect.mood}

==================================================

PURPOSE

${data.detect.purpose}

==================================================

CAMERA & LIGHTING

${camera}

==================================================

PRINT SPECIFICATION

${printing}

==================================================

AI OPTIMIZATION

${aiOptimization}

==================================================

NEGATIVE PROMPT

${negative}

==================================================

OUTPUT REQUIREMENTS

Ultra HD

8K Resolution

HDR

Professional Print Ready

Commercial Quality

Award Winning

Best Quality

Masterpiece

==================================================

Generated by PromptForge AI v4
`;

}


/* =====================================================
   UPDATE DETECT RESULT
===================================================== */

function updateDetectResult(result) {

    document.getElementById("detectCategory").textContent =
        result.category;

    document.getElementById("detectStyle").textContent =
        result.style;

    document.getElementById("detectColor").textContent =
        result.color;

    document.getElementById("detectAudience").textContent =
        result.audience;

}
